{"uuid": "62b84e10-de4d-45c6-9002-686dff2d272f", "children": ["8c307e0f-2a85-4a70-a7b2-2a0a69235389"], "befores": [{"name": "setup", "status": "passed", "start": 1681123685214, "stop": 1681123693343}], "afters": [{"name": "setup::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: disconnected: not connected to DevTools\n  (failed to check if window was closed: disconnected: not connected to DevTools)\n  (Session info: chrome=112.0.5615.49)\nStacktrace:\nBacktrace:\n\tGetHandleVerifier [0x0081DCE3+50899]\n\t(No symbol) [0x007AE111]\n\t(No symbol) [0x006B5588]\n\t(No symbol) [0x006A7CB6]\n\t(No symbol) [0x006A79D9]\n\t(No symbol) [0x006B6990]\n\t(No symbol) [0x0070DB9C]\n\t(No symbol) [0x006FB6F6]\n\t(No symbol) [0x006D7708]\n\t(No symbol) [0x006D886D]\n\tGetHandleVerifier [0x00A83EAE+2566302]\n\tGetHandleVerifier [0x00AB92B1+2784417]\n\tGetHandleVerifier [0x00AB327C+2759788]\n\tGetHandleVerifier [0x008B5740+672048]\n\t(No symbol) [0x007B8872]\n\t(No symbol) [0x007B41C8]\n\t(No symbol) [0x007B42AB]\n\t(No symbol) [0x007A71B7]\n\tBaseThreadInitThunk [0x77376BD9+25]\n\tRtlGetFullPathName_UEx [0x77C88FD2+1218]\n\tRtlGetFullPathName_UEx [0x77C88F9D+1165]\n\n", "trace": "  File \"C:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\allure_commons\\_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"C:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 917, in _teardown_yield_fixture\n    next(it)\n  File \"D:\\Python_Selenium_Practice\\TestScript\\conftest.py\", line 50, in setup\n    allure.attach(driver.get_screenshot_as_png(), name=\"../Screenshots\"+inspect.stack()[1][3], attachment_type=AttachmentType.PNG)\n  File \"C:\\Users\\Admin\\AppData\\Roaming\\Python\\Python310\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 927, in get_screenshot_as_png\n    return b64decode(self.get_screenshot_as_base64().encode(\"ascii\"))\n  File \"C:\\Users\\Admin\\AppData\\Roaming\\Python\\Python310\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 938, in get_screenshot_as_base64\n    return self.execute(Command.SCREENSHOT)[\"value\"]\n  File \"C:\\Users\\Admin\\AppData\\Roaming\\Python\\Python310\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 440, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Admin\\AppData\\Roaming\\Python\\Python310\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1681123740338, "stop": 1681123740338}], "start": 1681123685214, "stop": 1681123740338}